// Code generated by mockery v2.49.1. DO NOT EDIT.

package otel

import mock "github.com/stretchr/testify/mock"

// MockExporterOption is an autogenerated mock type for the ExporterOption type
type MockExporterOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockExporterOption) Execute(_a0 *config) {
	_m.Called(_a0)
}

// NewMockExporterOption creates a new instance of MockExporterOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExporterOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExporterOption {
	mock := &MockExporterOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
