template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/casbin/casbin/v2:
    config:
      all: false
      dir: mocks/mockcasbin
      structname: Mock{{.InterfaceName}}
      filename: "mock_{{.InterfaceName}}.go"
      pkgname: mockcasbin
    interfaces:
      IEnforcer: {}
  github.com/redis/go-redis/v9:
    config:
      all: false
      dir: mocks/mockredis
      structname: Mock{{.InterfaceName}}
      filename: "mock_{{.InterfaceName}}.go"
      pkgname: mockredis
    interfaces:
      Cmdable: {}
      Pipeliner: {}
      UniversalClient: {}
  github.com/viebiz/lit:
    config:
      all: true
      dir: '{{.InterfaceDir}}'
      structname: Mock{{.InterfaceName}}
      filename: "mock_{{.InterfaceName}}.go"
      pkgname: '{{.SrcPackageName}}'
      recursive: true
