// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package lit

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRoute creates a new instance of MockRoute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoute(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoute {
	mock := &MockRoute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoute is an autogenerated mock type for the Route type
type MockRoute struct {
	mock.Mock
}

type MockRoute_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoute) EXPECT() *MockRoute_Expecter {
	return &MockRoute_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockRoute
func (_mock *MockRoute) Delete(relativePath string, handler HandlerFunc, middleware ...HandlerFunc) Route {
	// HandlerFunc
	_va := make([]interface{}, len(middleware))
	for _i := range middleware {
		_va[_i] = middleware[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, relativePath, handler)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 Route
	if returnFunc, ok := ret.Get(0).(func(string, HandlerFunc, ...HandlerFunc) Route); ok {
		r0 = returnFunc(relativePath, handler, middleware...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Route)
		}
	}
	return r0
}

// MockRoute_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoute_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - relativePath string
//   - handler HandlerFunc
//   - middleware ...HandlerFunc
func (_e *MockRoute_Expecter) Delete(relativePath interface{}, handler interface{}, middleware ...interface{}) *MockRoute_Delete_Call {
	return &MockRoute_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{relativePath, handler}, middleware...)...)}
}

func (_c *MockRoute_Delete_Call) Run(run func(relativePath string, handler HandlerFunc, middleware ...HandlerFunc)) *MockRoute_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 HandlerFunc
		if args[1] != nil {
			arg1 = args[1].(HandlerFunc)
		}
		var arg2 []HandlerFunc
		variadicArgs := make([]HandlerFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(HandlerFunc)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRoute_Delete_Call) Return(route Route) *MockRoute_Delete_Call {
	_c.Call.Return(route)
	return _c
}

func (_c *MockRoute_Delete_Call) RunAndReturn(run func(relativePath string, handler HandlerFunc, middleware ...HandlerFunc) Route) *MockRoute_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRoute
func (_mock *MockRoute) Get(relativePath string, handler HandlerFunc, middleware ...HandlerFunc) Route {
	// HandlerFunc
	_va := make([]interface{}, len(middleware))
	for _i := range middleware {
		_va[_i] = middleware[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, relativePath, handler)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 Route
	if returnFunc, ok := ret.Get(0).(func(string, HandlerFunc, ...HandlerFunc) Route); ok {
		r0 = returnFunc(relativePath, handler, middleware...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Route)
		}
	}
	return r0
}

// MockRoute_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRoute_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - relativePath string
//   - handler HandlerFunc
//   - middleware ...HandlerFunc
func (_e *MockRoute_Expecter) Get(relativePath interface{}, handler interface{}, middleware ...interface{}) *MockRoute_Get_Call {
	return &MockRoute_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{relativePath, handler}, middleware...)...)}
}

func (_c *MockRoute_Get_Call) Run(run func(relativePath string, handler HandlerFunc, middleware ...HandlerFunc)) *MockRoute_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 HandlerFunc
		if args[1] != nil {
			arg1 = args[1].(HandlerFunc)
		}
		var arg2 []HandlerFunc
		variadicArgs := make([]HandlerFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(HandlerFunc)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRoute_Get_Call) Return(route Route) *MockRoute_Get_Call {
	_c.Call.Return(route)
	return _c
}

func (_c *MockRoute_Get_Call) RunAndReturn(run func(relativePath string, handler HandlerFunc, middleware ...HandlerFunc) Route) *MockRoute_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Handle provides a mock function for the type MockRoute
func (_mock *MockRoute) Handle(method string, relativePath string, handler HandlerFunc, middleware ...HandlerFunc) Route {
	// HandlerFunc
	_va := make([]interface{}, len(middleware))
	for _i := range middleware {
		_va[_i] = middleware[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, method, relativePath, handler)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 Route
	if returnFunc, ok := ret.Get(0).(func(string, string, HandlerFunc, ...HandlerFunc) Route); ok {
		r0 = returnFunc(method, relativePath, handler, middleware...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Route)
		}
	}
	return r0
}

// MockRoute_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockRoute_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - method string
//   - relativePath string
//   - handler HandlerFunc
//   - middleware ...HandlerFunc
func (_e *MockRoute_Expecter) Handle(method interface{}, relativePath interface{}, handler interface{}, middleware ...interface{}) *MockRoute_Handle_Call {
	return &MockRoute_Handle_Call{Call: _e.mock.On("Handle",
		append([]interface{}{method, relativePath, handler}, middleware...)...)}
}

func (_c *MockRoute_Handle_Call) Run(run func(method string, relativePath string, handler HandlerFunc, middleware ...HandlerFunc)) *MockRoute_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 HandlerFunc
		if args[2] != nil {
			arg2 = args[2].(HandlerFunc)
		}
		var arg3 []HandlerFunc
		variadicArgs := make([]HandlerFunc, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(HandlerFunc)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockRoute_Handle_Call) Return(route Route) *MockRoute_Handle_Call {
	_c.Call.Return(route)
	return _c
}

func (_c *MockRoute_Handle_Call) RunAndReturn(run func(method string, relativePath string, handler HandlerFunc, middleware ...HandlerFunc) Route) *MockRoute_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// Head provides a mock function for the type MockRoute
func (_mock *MockRoute) Head(relativePath string, handler HandlerFunc, middleware ...HandlerFunc) Route {
	// HandlerFunc
	_va := make([]interface{}, len(middleware))
	for _i := range middleware {
		_va[_i] = middleware[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, relativePath, handler)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Head")
	}

	var r0 Route
	if returnFunc, ok := ret.Get(0).(func(string, HandlerFunc, ...HandlerFunc) Route); ok {
		r0 = returnFunc(relativePath, handler, middleware...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Route)
		}
	}
	return r0
}

// MockRoute_Head_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Head'
type MockRoute_Head_Call struct {
	*mock.Call
}

// Head is a helper method to define mock.On call
//   - relativePath string
//   - handler HandlerFunc
//   - middleware ...HandlerFunc
func (_e *MockRoute_Expecter) Head(relativePath interface{}, handler interface{}, middleware ...interface{}) *MockRoute_Head_Call {
	return &MockRoute_Head_Call{Call: _e.mock.On("Head",
		append([]interface{}{relativePath, handler}, middleware...)...)}
}

func (_c *MockRoute_Head_Call) Run(run func(relativePath string, handler HandlerFunc, middleware ...HandlerFunc)) *MockRoute_Head_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 HandlerFunc
		if args[1] != nil {
			arg1 = args[1].(HandlerFunc)
		}
		var arg2 []HandlerFunc
		variadicArgs := make([]HandlerFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(HandlerFunc)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRoute_Head_Call) Return(route Route) *MockRoute_Head_Call {
	_c.Call.Return(route)
	return _c
}

func (_c *MockRoute_Head_Call) RunAndReturn(run func(relativePath string, handler HandlerFunc, middleware ...HandlerFunc) Route) *MockRoute_Head_Call {
	_c.Call.Return(run)
	return _c
}

// Match provides a mock function for the type MockRoute
func (_mock *MockRoute) Match(methods []string, relativePath string, handler HandlerFunc, middleware ...HandlerFunc) Route {
	// HandlerFunc
	_va := make([]interface{}, len(middleware))
	for _i := range middleware {
		_va[_i] = middleware[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, methods, relativePath, handler)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Match")
	}

	var r0 Route
	if returnFunc, ok := ret.Get(0).(func([]string, string, HandlerFunc, ...HandlerFunc) Route); ok {
		r0 = returnFunc(methods, relativePath, handler, middleware...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Route)
		}
	}
	return r0
}

// MockRoute_Match_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Match'
type MockRoute_Match_Call struct {
	*mock.Call
}

// Match is a helper method to define mock.On call
//   - methods []string
//   - relativePath string
//   - handler HandlerFunc
//   - middleware ...HandlerFunc
func (_e *MockRoute_Expecter) Match(methods interface{}, relativePath interface{}, handler interface{}, middleware ...interface{}) *MockRoute_Match_Call {
	return &MockRoute_Match_Call{Call: _e.mock.On("Match",
		append([]interface{}{methods, relativePath, handler}, middleware...)...)}
}

func (_c *MockRoute_Match_Call) Run(run func(methods []string, relativePath string, handler HandlerFunc, middleware ...HandlerFunc)) *MockRoute_Match_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 HandlerFunc
		if args[2] != nil {
			arg2 = args[2].(HandlerFunc)
		}
		var arg3 []HandlerFunc
		variadicArgs := make([]HandlerFunc, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(HandlerFunc)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockRoute_Match_Call) Return(route Route) *MockRoute_Match_Call {
	_c.Call.Return(route)
	return _c
}

func (_c *MockRoute_Match_Call) RunAndReturn(run func(methods []string, relativePath string, handler HandlerFunc, middleware ...HandlerFunc) Route) *MockRoute_Match_Call {
	_c.Call.Return(run)
	return _c
}

// Options provides a mock function for the type MockRoute
func (_mock *MockRoute) Options(relativePath string, handler HandlerFunc, middleware ...HandlerFunc) Route {
	// HandlerFunc
	_va := make([]interface{}, len(middleware))
	for _i := range middleware {
		_va[_i] = middleware[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, relativePath, handler)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 Route
	if returnFunc, ok := ret.Get(0).(func(string, HandlerFunc, ...HandlerFunc) Route); ok {
		r0 = returnFunc(relativePath, handler, middleware...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Route)
		}
	}
	return r0
}

// MockRoute_Options_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Options'
type MockRoute_Options_Call struct {
	*mock.Call
}

// Options is a helper method to define mock.On call
//   - relativePath string
//   - handler HandlerFunc
//   - middleware ...HandlerFunc
func (_e *MockRoute_Expecter) Options(relativePath interface{}, handler interface{}, middleware ...interface{}) *MockRoute_Options_Call {
	return &MockRoute_Options_Call{Call: _e.mock.On("Options",
		append([]interface{}{relativePath, handler}, middleware...)...)}
}

func (_c *MockRoute_Options_Call) Run(run func(relativePath string, handler HandlerFunc, middleware ...HandlerFunc)) *MockRoute_Options_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 HandlerFunc
		if args[1] != nil {
			arg1 = args[1].(HandlerFunc)
		}
		var arg2 []HandlerFunc
		variadicArgs := make([]HandlerFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(HandlerFunc)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRoute_Options_Call) Return(route Route) *MockRoute_Options_Call {
	_c.Call.Return(route)
	return _c
}

func (_c *MockRoute_Options_Call) RunAndReturn(run func(relativePath string, handler HandlerFunc, middleware ...HandlerFunc) Route) *MockRoute_Options_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function for the type MockRoute
func (_mock *MockRoute) Patch(relativePath string, handler HandlerFunc, middleware ...HandlerFunc) Route {
	// HandlerFunc
	_va := make([]interface{}, len(middleware))
	for _i := range middleware {
		_va[_i] = middleware[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, relativePath, handler)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 Route
	if returnFunc, ok := ret.Get(0).(func(string, HandlerFunc, ...HandlerFunc) Route); ok {
		r0 = returnFunc(relativePath, handler, middleware...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Route)
		}
	}
	return r0
}

// MockRoute_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockRoute_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - relativePath string
//   - handler HandlerFunc
//   - middleware ...HandlerFunc
func (_e *MockRoute_Expecter) Patch(relativePath interface{}, handler interface{}, middleware ...interface{}) *MockRoute_Patch_Call {
	return &MockRoute_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{relativePath, handler}, middleware...)...)}
}

func (_c *MockRoute_Patch_Call) Run(run func(relativePath string, handler HandlerFunc, middleware ...HandlerFunc)) *MockRoute_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 HandlerFunc
		if args[1] != nil {
			arg1 = args[1].(HandlerFunc)
		}
		var arg2 []HandlerFunc
		variadicArgs := make([]HandlerFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(HandlerFunc)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRoute_Patch_Call) Return(route Route) *MockRoute_Patch_Call {
	_c.Call.Return(route)
	return _c
}

func (_c *MockRoute_Patch_Call) RunAndReturn(run func(relativePath string, handler HandlerFunc, middleware ...HandlerFunc) Route) *MockRoute_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Post provides a mock function for the type MockRoute
func (_mock *MockRoute) Post(relativePath string, handler HandlerFunc, middleware ...HandlerFunc) Route {
	// HandlerFunc
	_va := make([]interface{}, len(middleware))
	for _i := range middleware {
		_va[_i] = middleware[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, relativePath, handler)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 Route
	if returnFunc, ok := ret.Get(0).(func(string, HandlerFunc, ...HandlerFunc) Route); ok {
		r0 = returnFunc(relativePath, handler, middleware...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Route)
		}
	}
	return r0
}

// MockRoute_Post_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Post'
type MockRoute_Post_Call struct {
	*mock.Call
}

// Post is a helper method to define mock.On call
//   - relativePath string
//   - handler HandlerFunc
//   - middleware ...HandlerFunc
func (_e *MockRoute_Expecter) Post(relativePath interface{}, handler interface{}, middleware ...interface{}) *MockRoute_Post_Call {
	return &MockRoute_Post_Call{Call: _e.mock.On("Post",
		append([]interface{}{relativePath, handler}, middleware...)...)}
}

func (_c *MockRoute_Post_Call) Run(run func(relativePath string, handler HandlerFunc, middleware ...HandlerFunc)) *MockRoute_Post_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 HandlerFunc
		if args[1] != nil {
			arg1 = args[1].(HandlerFunc)
		}
		var arg2 []HandlerFunc
		variadicArgs := make([]HandlerFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(HandlerFunc)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRoute_Post_Call) Return(route Route) *MockRoute_Post_Call {
	_c.Call.Return(route)
	return _c
}

func (_c *MockRoute_Post_Call) RunAndReturn(run func(relativePath string, handler HandlerFunc, middleware ...HandlerFunc) Route) *MockRoute_Post_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockRoute
func (_mock *MockRoute) Put(relativePath string, handler HandlerFunc, middleware ...HandlerFunc) Route {
	// HandlerFunc
	_va := make([]interface{}, len(middleware))
	for _i := range middleware {
		_va[_i] = middleware[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, relativePath, handler)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 Route
	if returnFunc, ok := ret.Get(0).(func(string, HandlerFunc, ...HandlerFunc) Route); ok {
		r0 = returnFunc(relativePath, handler, middleware...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Route)
		}
	}
	return r0
}

// MockRoute_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockRoute_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - relativePath string
//   - handler HandlerFunc
//   - middleware ...HandlerFunc
func (_e *MockRoute_Expecter) Put(relativePath interface{}, handler interface{}, middleware ...interface{}) *MockRoute_Put_Call {
	return &MockRoute_Put_Call{Call: _e.mock.On("Put",
		append([]interface{}{relativePath, handler}, middleware...)...)}
}

func (_c *MockRoute_Put_Call) Run(run func(relativePath string, handler HandlerFunc, middleware ...HandlerFunc)) *MockRoute_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 HandlerFunc
		if args[1] != nil {
			arg1 = args[1].(HandlerFunc)
		}
		var arg2 []HandlerFunc
		variadicArgs := make([]HandlerFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(HandlerFunc)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRoute_Put_Call) Return(route Route) *MockRoute_Put_Call {
	_c.Call.Return(route)
	return _c
}

func (_c *MockRoute_Put_Call) RunAndReturn(run func(relativePath string, handler HandlerFunc, middleware ...HandlerFunc) Route) *MockRoute_Put_Call {
	_c.Call.Return(run)
	return _c
}

// StaticFS provides a mock function for the type MockRoute
func (_mock *MockRoute) StaticFS(relativePath string, fs http.FileSystem) Route {
	ret := _mock.Called(relativePath, fs)

	if len(ret) == 0 {
		panic("no return value specified for StaticFS")
	}

	var r0 Route
	if returnFunc, ok := ret.Get(0).(func(string, http.FileSystem) Route); ok {
		r0 = returnFunc(relativePath, fs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Route)
		}
	}
	return r0
}

// MockRoute_StaticFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StaticFS'
type MockRoute_StaticFS_Call struct {
	*mock.Call
}

// StaticFS is a helper method to define mock.On call
//   - relativePath string
//   - fs http.FileSystem
func (_e *MockRoute_Expecter) StaticFS(relativePath interface{}, fs interface{}) *MockRoute_StaticFS_Call {
	return &MockRoute_StaticFS_Call{Call: _e.mock.On("StaticFS", relativePath, fs)}
}

func (_c *MockRoute_StaticFS_Call) Run(run func(relativePath string, fs http.FileSystem)) *MockRoute_StaticFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 http.FileSystem
		if args[1] != nil {
			arg1 = args[1].(http.FileSystem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoute_StaticFS_Call) Return(route Route) *MockRoute_StaticFS_Call {
	_c.Call.Return(route)
	return _c
}

func (_c *MockRoute_StaticFS_Call) RunAndReturn(run func(relativePath string, fs http.FileSystem) Route) *MockRoute_StaticFS_Call {
	_c.Call.Return(run)
	return _c
}

// StaticFileFS provides a mock function for the type MockRoute
func (_mock *MockRoute) StaticFileFS(relativePath string, filepath string, fs http.FileSystem) Route {
	ret := _mock.Called(relativePath, filepath, fs)

	if len(ret) == 0 {
		panic("no return value specified for StaticFileFS")
	}

	var r0 Route
	if returnFunc, ok := ret.Get(0).(func(string, string, http.FileSystem) Route); ok {
		r0 = returnFunc(relativePath, filepath, fs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Route)
		}
	}
	return r0
}

// MockRoute_StaticFileFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StaticFileFS'
type MockRoute_StaticFileFS_Call struct {
	*mock.Call
}

// StaticFileFS is a helper method to define mock.On call
//   - relativePath string
//   - filepath string
//   - fs http.FileSystem
func (_e *MockRoute_Expecter) StaticFileFS(relativePath interface{}, filepath interface{}, fs interface{}) *MockRoute_StaticFileFS_Call {
	return &MockRoute_StaticFileFS_Call{Call: _e.mock.On("StaticFileFS", relativePath, filepath, fs)}
}

func (_c *MockRoute_StaticFileFS_Call) Run(run func(relativePath string, filepath string, fs http.FileSystem)) *MockRoute_StaticFileFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 http.FileSystem
		if args[2] != nil {
			arg2 = args[2].(http.FileSystem)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRoute_StaticFileFS_Call) Return(route Route) *MockRoute_StaticFileFS_Call {
	_c.Call.Return(route)
	return _c
}

func (_c *MockRoute_StaticFileFS_Call) RunAndReturn(run func(relativePath string, filepath string, fs http.FileSystem) Route) *MockRoute_StaticFileFS_Call {
	_c.Call.Return(run)
	return _c
}

// Use provides a mock function for the type MockRoute
func (_mock *MockRoute) Use(middlewares ...HandlerFunc) {
	// HandlerFunc
	_va := make([]interface{}, len(middlewares))
	for _i := range middlewares {
		_va[_i] = middlewares[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// MockRoute_Use_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Use'
type MockRoute_Use_Call struct {
	*mock.Call
}

// Use is a helper method to define mock.On call
//   - middlewares ...HandlerFunc
func (_e *MockRoute_Expecter) Use(middlewares ...interface{}) *MockRoute_Use_Call {
	return &MockRoute_Use_Call{Call: _e.mock.On("Use",
		append([]interface{}{}, middlewares...)...)}
}

func (_c *MockRoute_Use_Call) Run(run func(middlewares ...HandlerFunc)) *MockRoute_Use_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []HandlerFunc
		variadicArgs := make([]HandlerFunc, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(HandlerFunc)
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockRoute_Use_Call) Return() *MockRoute_Use_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRoute_Use_Call) RunAndReturn(run func(middlewares ...HandlerFunc)) *MockRoute_Use_Call {
	_c.Run(run)
	return _c
}
