// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package lit

import (
	"context"
	"mime/multipart"
	"net/http"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockContext creates a new instance of MockContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContext {
	mock := &MockContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContext is an autogenerated mock type for the Context type
type MockContext struct {
	mock.Mock
}

type MockContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContext) EXPECT() *MockContext_Expecter {
	return &MockContext_Expecter{mock: &_m.Mock}
}

// Abort provides a mock function for the type MockContext
func (_mock *MockContext) Abort() {
	_mock.Called()
	return
}

// MockContext_Abort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Abort'
type MockContext_Abort_Call struct {
	*mock.Call
}

// Abort is a helper method to define mock.On call
func (_e *MockContext_Expecter) Abort() *MockContext_Abort_Call {
	return &MockContext_Abort_Call{Call: _e.mock.On("Abort")}
}

func (_c *MockContext_Abort_Call) Run(run func()) *MockContext_Abort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Abort_Call) Return() *MockContext_Abort_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContext_Abort_Call) RunAndReturn(run func()) *MockContext_Abort_Call {
	_c.Run(run)
	return _c
}

// Bind provides a mock function for the type MockContext
func (_mock *MockContext) Bind(obj interface{}) error {
	ret := _mock.Called(obj)

	if len(ret) == 0 {
		panic("no return value specified for Bind")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = returnFunc(obj)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_Bind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bind'
type MockContext_Bind_Call struct {
	*mock.Call
}

// Bind is a helper method to define mock.On call
//   - obj interface{}
func (_e *MockContext_Expecter) Bind(obj interface{}) *MockContext_Bind_Call {
	return &MockContext_Bind_Call{Call: _e.mock.On("Bind", obj)}
}

func (_c *MockContext_Bind_Call) Run(run func(obj interface{})) *MockContext_Bind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_Bind_Call) Return(err error) *MockContext_Bind_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_Bind_Call) RunAndReturn(run func(obj interface{}) error) *MockContext_Bind_Call {
	_c.Call.Return(run)
	return _c
}

// Deadline provides a mock function for the type MockContext
func (_mock *MockContext) Deadline() (time.Time, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Deadline")
	}

	var r0 time.Time
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (time.Time, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockContext_Deadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deadline'
type MockContext_Deadline_Call struct {
	*mock.Call
}

// Deadline is a helper method to define mock.On call
func (_e *MockContext_Expecter) Deadline() *MockContext_Deadline_Call {
	return &MockContext_Deadline_Call{Call: _e.mock.On("Deadline")}
}

func (_c *MockContext_Deadline_Call) Run(run func()) *MockContext_Deadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Deadline_Call) Return(deadline time.Time, ok bool) *MockContext_Deadline_Call {
	_c.Call.Return(deadline, ok)
	return _c
}

func (_c *MockContext_Deadline_Call) RunAndReturn(run func() (time.Time, bool)) *MockContext_Deadline_Call {
	_c.Call.Return(run)
	return _c
}

// Done provides a mock function for the type MockContext
func (_mock *MockContext) Done() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockContext_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockContext_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockContext_Expecter) Done() *MockContext_Done_Call {
	return &MockContext_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *MockContext_Done_Call) Run(run func()) *MockContext_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Done_Call) Return(valCh <-chan struct{}) *MockContext_Done_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockContext_Done_Call) RunAndReturn(run func() <-chan struct{}) *MockContext_Done_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function for the type MockContext
func (_mock *MockContext) Err() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockContext_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockContext_Expecter) Err() *MockContext_Err_Call {
	return &MockContext_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MockContext_Err_Call) Run(run func()) *MockContext_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Err_Call) Return(err error) *MockContext_Err_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_Err_Call) RunAndReturn(run func() error) *MockContext_Err_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function for the type MockContext
func (_mock *MockContext) Error(err error) {
	_mock.Called(err)
	return
}

// MockContext_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockContext_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - err error
func (_e *MockContext_Expecter) Error(err interface{}) *MockContext_Error_Call {
	return &MockContext_Error_Call{Call: _e.mock.On("Error", err)}
}

func (_c *MockContext_Error_Call) Run(run func(err error)) *MockContext_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_Error_Call) Return() *MockContext_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContext_Error_Call) RunAndReturn(run func(err error)) *MockContext_Error_Call {
	_c.Run(run)
	return _c
}

// FormFile provides a mock function for the type MockContext
func (_mock *MockContext) FormFile(name string) (*multipart.FileHeader, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for FormFile")
	}

	var r0 *multipart.FileHeader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*multipart.FileHeader, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *multipart.FileHeader); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*multipart.FileHeader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContext_FormFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FormFile'
type MockContext_FormFile_Call struct {
	*mock.Call
}

// FormFile is a helper method to define mock.On call
//   - name string
func (_e *MockContext_Expecter) FormFile(name interface{}) *MockContext_FormFile_Call {
	return &MockContext_FormFile_Call{Call: _e.mock.On("FormFile", name)}
}

func (_c *MockContext_FormFile_Call) Run(run func(name string)) *MockContext_FormFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_FormFile_Call) Return(fileHeader *multipart.FileHeader, err error) *MockContext_FormFile_Call {
	_c.Call.Return(fileHeader, err)
	return _c
}

func (_c *MockContext_FormFile_Call) RunAndReturn(run func(name string) (*multipart.FileHeader, error)) *MockContext_FormFile_Call {
	_c.Call.Return(run)
	return _c
}

// FullPath provides a mock function for the type MockContext
func (_mock *MockContext) FullPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FullPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockContext_FullPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FullPath'
type MockContext_FullPath_Call struct {
	*mock.Call
}

// FullPath is a helper method to define mock.On call
func (_e *MockContext_Expecter) FullPath() *MockContext_FullPath_Call {
	return &MockContext_FullPath_Call{Call: _e.mock.On("FullPath")}
}

func (_c *MockContext_FullPath_Call) Run(run func()) *MockContext_FullPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_FullPath_Call) Return(s string) *MockContext_FullPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockContext_FullPath_Call) RunAndReturn(run func() string) *MockContext_FullPath_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockContext
func (_mock *MockContext) Get(key string) (any, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (any, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockContext_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockContext_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockContext_Expecter) Get(key interface{}) *MockContext_Get_Call {
	return &MockContext_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockContext_Get_Call) Run(run func(key string)) *MockContext_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_Get_Call) Return(value any, exists bool) *MockContext_Get_Call {
	_c.Call.Return(value, exists)
	return _c
}

func (_c *MockContext_Get_Call) RunAndReturn(run func(key string) (any, bool)) *MockContext_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function for the type MockContext
func (_mock *MockContext) Header(key string, value string) {
	_mock.Called(key, value)
	return
}

// MockContext_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type MockContext_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *MockContext_Expecter) Header(key interface{}, value interface{}) *MockContext_Header_Call {
	return &MockContext_Header_Call{Call: _e.mock.On("Header", key, value)}
}

func (_c *MockContext_Header_Call) Run(run func(key string, value string)) *MockContext_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContext_Header_Call) Return() *MockContext_Header_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContext_Header_Call) RunAndReturn(run func(key string, value string)) *MockContext_Header_Call {
	_c.Run(run)
	return _c
}

// JSON provides a mock function for the type MockContext
func (_mock *MockContext) JSON(code int, obj any) error {
	ret := _mock.Called(code, obj)

	if len(ret) == 0 {
		panic("no return value specified for JSON")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, any) error); ok {
		r0 = returnFunc(code, obj)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_JSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JSON'
type MockContext_JSON_Call struct {
	*mock.Call
}

// JSON is a helper method to define mock.On call
//   - code int
//   - obj any
func (_e *MockContext_Expecter) JSON(code interface{}, obj interface{}) *MockContext_JSON_Call {
	return &MockContext_JSON_Call{Call: _e.mock.On("JSON", code, obj)}
}

func (_c *MockContext_JSON_Call) Run(run func(code int, obj any)) *MockContext_JSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContext_JSON_Call) Return(err error) *MockContext_JSON_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_JSON_Call) RunAndReturn(run func(code int, obj any) error) *MockContext_JSON_Call {
	_c.Call.Return(run)
	return _c
}

// MultipartForm provides a mock function for the type MockContext
func (_mock *MockContext) MultipartForm() (*multipart.Form, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MultipartForm")
	}

	var r0 *multipart.Form
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*multipart.Form, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *multipart.Form); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*multipart.Form)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContext_MultipartForm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MultipartForm'
type MockContext_MultipartForm_Call struct {
	*mock.Call
}

// MultipartForm is a helper method to define mock.On call
func (_e *MockContext_Expecter) MultipartForm() *MockContext_MultipartForm_Call {
	return &MockContext_MultipartForm_Call{Call: _e.mock.On("MultipartForm")}
}

func (_c *MockContext_MultipartForm_Call) Run(run func()) *MockContext_MultipartForm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_MultipartForm_Call) Return(form *multipart.Form, err error) *MockContext_MultipartForm_Call {
	_c.Call.Return(form, err)
	return _c
}

func (_c *MockContext_MultipartForm_Call) RunAndReturn(run func() (*multipart.Form, error)) *MockContext_MultipartForm_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function for the type MockContext
func (_mock *MockContext) Next() {
	_mock.Called()
	return
}

// MockContext_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockContext_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockContext_Expecter) Next() *MockContext_Next_Call {
	return &MockContext_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockContext_Next_Call) Run(run func()) *MockContext_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Next_Call) Return() *MockContext_Next_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContext_Next_Call) RunAndReturn(run func()) *MockContext_Next_Call {
	_c.Run(run)
	return _c
}

// NoContent provides a mock function for the type MockContext
func (_mock *MockContext) NoContent(status int) error {
	ret := _mock.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for NoContent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_NoContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NoContent'
type MockContext_NoContent_Call struct {
	*mock.Call
}

// NoContent is a helper method to define mock.On call
//   - status int
func (_e *MockContext_Expecter) NoContent(status interface{}) *MockContext_NoContent_Call {
	return &MockContext_NoContent_Call{Call: _e.mock.On("NoContent", status)}
}

func (_c *MockContext_NoContent_Call) Run(run func(status int)) *MockContext_NoContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_NoContent_Call) Return(err error) *MockContext_NoContent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_NoContent_Call) RunAndReturn(run func(status int) error) *MockContext_NoContent_Call {
	_c.Call.Return(run)
	return _c
}

// Param provides a mock function for the type MockContext
func (_mock *MockContext) Param(key string) string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Param")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockContext_Param_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Param'
type MockContext_Param_Call struct {
	*mock.Call
}

// Param is a helper method to define mock.On call
//   - key string
func (_e *MockContext_Expecter) Param(key interface{}) *MockContext_Param_Call {
	return &MockContext_Param_Call{Call: _e.mock.On("Param", key)}
}

func (_c *MockContext_Param_Call) Run(run func(key string)) *MockContext_Param_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_Param_Call) Return(s string) *MockContext_Param_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockContext_Param_Call) RunAndReturn(run func(key string) string) *MockContext_Param_Call {
	_c.Call.Return(run)
	return _c
}

// ParamWithCallback provides a mock function for the type MockContext
func (_mock *MockContext) ParamWithCallback(key string, callback func() string) string {
	ret := _mock.Called(key, callback)

	if len(ret) == 0 {
		panic("no return value specified for ParamWithCallback")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, func() string) string); ok {
		r0 = returnFunc(key, callback)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockContext_ParamWithCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParamWithCallback'
type MockContext_ParamWithCallback_Call struct {
	*mock.Call
}

// ParamWithCallback is a helper method to define mock.On call
//   - key string
//   - callback func() string
func (_e *MockContext_Expecter) ParamWithCallback(key interface{}, callback interface{}) *MockContext_ParamWithCallback_Call {
	return &MockContext_ParamWithCallback_Call{Call: _e.mock.On("ParamWithCallback", key, callback)}
}

func (_c *MockContext_ParamWithCallback_Call) Run(run func(key string, callback func() string)) *MockContext_ParamWithCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func() string
		if args[1] != nil {
			arg1 = args[1].(func() string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContext_ParamWithCallback_Call) Return(s string) *MockContext_ParamWithCallback_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockContext_ParamWithCallback_Call) RunAndReturn(run func(key string, callback func() string) string) *MockContext_ParamWithCallback_Call {
	_c.Call.Return(run)
	return _c
}

// ParamWithDefault provides a mock function for the type MockContext
func (_mock *MockContext) ParamWithDefault(key string, defaultValue string) string {
	ret := _mock.Called(key, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for ParamWithDefault")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(key, defaultValue)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockContext_ParamWithDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParamWithDefault'
type MockContext_ParamWithDefault_Call struct {
	*mock.Call
}

// ParamWithDefault is a helper method to define mock.On call
//   - key string
//   - defaultValue string
func (_e *MockContext_Expecter) ParamWithDefault(key interface{}, defaultValue interface{}) *MockContext_ParamWithDefault_Call {
	return &MockContext_ParamWithDefault_Call{Call: _e.mock.On("ParamWithDefault", key, defaultValue)}
}

func (_c *MockContext_ParamWithDefault_Call) Run(run func(key string, defaultValue string)) *MockContext_ParamWithDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContext_ParamWithDefault_Call) Return(s string) *MockContext_ParamWithDefault_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockContext_ParamWithDefault_Call) RunAndReturn(run func(key string, defaultValue string) string) *MockContext_ParamWithDefault_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockContext
func (_mock *MockContext) Query(key string) string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockContext_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockContext_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - key string
func (_e *MockContext_Expecter) Query(key interface{}) *MockContext_Query_Call {
	return &MockContext_Query_Call{Call: _e.mock.On("Query", key)}
}

func (_c *MockContext_Query_Call) Run(run func(key string)) *MockContext_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_Query_Call) Return(s string) *MockContext_Query_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockContext_Query_Call) RunAndReturn(run func(key string) string) *MockContext_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryWithCallback provides a mock function for the type MockContext
func (_mock *MockContext) QueryWithCallback(key string, callback func() string) string {
	ret := _mock.Called(key, callback)

	if len(ret) == 0 {
		panic("no return value specified for QueryWithCallback")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, func() string) string); ok {
		r0 = returnFunc(key, callback)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockContext_QueryWithCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryWithCallback'
type MockContext_QueryWithCallback_Call struct {
	*mock.Call
}

// QueryWithCallback is a helper method to define mock.On call
//   - key string
//   - callback func() string
func (_e *MockContext_Expecter) QueryWithCallback(key interface{}, callback interface{}) *MockContext_QueryWithCallback_Call {
	return &MockContext_QueryWithCallback_Call{Call: _e.mock.On("QueryWithCallback", key, callback)}
}

func (_c *MockContext_QueryWithCallback_Call) Run(run func(key string, callback func() string)) *MockContext_QueryWithCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func() string
		if args[1] != nil {
			arg1 = args[1].(func() string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContext_QueryWithCallback_Call) Return(s string) *MockContext_QueryWithCallback_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockContext_QueryWithCallback_Call) RunAndReturn(run func(key string, callback func() string) string) *MockContext_QueryWithCallback_Call {
	_c.Call.Return(run)
	return _c
}

// QueryWithDefault provides a mock function for the type MockContext
func (_mock *MockContext) QueryWithDefault(key string, defaultValue string) string {
	ret := _mock.Called(key, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for QueryWithDefault")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(key, defaultValue)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockContext_QueryWithDefault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryWithDefault'
type MockContext_QueryWithDefault_Call struct {
	*mock.Call
}

// QueryWithDefault is a helper method to define mock.On call
//   - key string
//   - defaultValue string
func (_e *MockContext_Expecter) QueryWithDefault(key interface{}, defaultValue interface{}) *MockContext_QueryWithDefault_Call {
	return &MockContext_QueryWithDefault_Call{Call: _e.mock.On("QueryWithDefault", key, defaultValue)}
}

func (_c *MockContext_QueryWithDefault_Call) Run(run func(key string, defaultValue string)) *MockContext_QueryWithDefault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContext_QueryWithDefault_Call) Return(s string) *MockContext_QueryWithDefault_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockContext_QueryWithDefault_Call) RunAndReturn(run func(key string, defaultValue string) string) *MockContext_QueryWithDefault_Call {
	_c.Call.Return(run)
	return _c
}

// Request provides a mock function for the type MockContext
func (_mock *MockContext) Request() *http.Request {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 *http.Request
	if returnFunc, ok := ret.Get(0).(func() *http.Request); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}
	return r0
}

// MockContext_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type MockContext_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
func (_e *MockContext_Expecter) Request() *MockContext_Request_Call {
	return &MockContext_Request_Call{Call: _e.mock.On("Request")}
}

func (_c *MockContext_Request_Call) Run(run func()) *MockContext_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Request_Call) Return(request *http.Request) *MockContext_Request_Call {
	_c.Call.Return(request)
	return _c
}

func (_c *MockContext_Request_Call) RunAndReturn(run func() *http.Request) *MockContext_Request_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockContext
func (_mock *MockContext) Set(key string, value any) {
	_mock.Called(key, value)
	return
}

// MockContext_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockContext_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value any
func (_e *MockContext_Expecter) Set(key interface{}, value interface{}) *MockContext_Set_Call {
	return &MockContext_Set_Call{Call: _e.mock.On("Set", key, value)}
}

func (_c *MockContext_Set_Call) Run(run func(key string, value any)) *MockContext_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContext_Set_Call) Return() *MockContext_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContext_Set_Call) RunAndReturn(run func(key string, value any)) *MockContext_Set_Call {
	_c.Run(run)
	return _c
}

// SetRequest provides a mock function for the type MockContext
func (_mock *MockContext) SetRequest(request *http.Request) {
	_mock.Called(request)
	return
}

// MockContext_SetRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRequest'
type MockContext_SetRequest_Call struct {
	*mock.Call
}

// SetRequest is a helper method to define mock.On call
//   - request *http.Request
func (_e *MockContext_Expecter) SetRequest(request interface{}) *MockContext_SetRequest_Call {
	return &MockContext_SetRequest_Call{Call: _e.mock.On("SetRequest", request)}
}

func (_c *MockContext_SetRequest_Call) Run(run func(request *http.Request)) *MockContext_SetRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_SetRequest_Call) Return() *MockContext_SetRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContext_SetRequest_Call) RunAndReturn(run func(request *http.Request)) *MockContext_SetRequest_Call {
	_c.Run(run)
	return _c
}

// SetRequestContext provides a mock function for the type MockContext
func (_mock *MockContext) SetRequestContext(ctx context.Context) *http.Request {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SetRequestContext")
	}

	var r0 *http.Request
	if returnFunc, ok := ret.Get(0).(func(context.Context) *http.Request); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}
	return r0
}

// MockContext_SetRequestContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRequestContext'
type MockContext_SetRequestContext_Call struct {
	*mock.Call
}

// SetRequestContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockContext_Expecter) SetRequestContext(ctx interface{}) *MockContext_SetRequestContext_Call {
	return &MockContext_SetRequestContext_Call{Call: _e.mock.On("SetRequestContext", ctx)}
}

func (_c *MockContext_SetRequestContext_Call) Run(run func(ctx context.Context)) *MockContext_SetRequestContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_SetRequestContext_Call) Return(request *http.Request) *MockContext_SetRequestContext_Call {
	_c.Call.Return(request)
	return _c
}

func (_c *MockContext_SetRequestContext_Call) RunAndReturn(run func(ctx context.Context) *http.Request) *MockContext_SetRequestContext_Call {
	_c.Call.Return(run)
	return _c
}

// SetWriter provides a mock function for the type MockContext
func (_mock *MockContext) SetWriter(w ResponseWriter) {
	_mock.Called(w)
	return
}

// MockContext_SetWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWriter'
type MockContext_SetWriter_Call struct {
	*mock.Call
}

// SetWriter is a helper method to define mock.On call
//   - w ResponseWriter
func (_e *MockContext_Expecter) SetWriter(w interface{}) *MockContext_SetWriter_Call {
	return &MockContext_SetWriter_Call{Call: _e.mock.On("SetWriter", w)}
}

func (_c *MockContext_SetWriter_Call) Run(run func(w ResponseWriter)) *MockContext_SetWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(ResponseWriter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_SetWriter_Call) Return() *MockContext_SetWriter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContext_SetWriter_Call) RunAndReturn(run func(w ResponseWriter)) *MockContext_SetWriter_Call {
	_c.Run(run)
	return _c
}

// Status provides a mock function for the type MockContext
func (_mock *MockContext) Status(code int) {
	_mock.Called(code)
	return
}

// MockContext_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockContext_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - code int
func (_e *MockContext_Expecter) Status(code interface{}) *MockContext_Status_Call {
	return &MockContext_Status_Call{Call: _e.mock.On("Status", code)}
}

func (_c *MockContext_Status_Call) Run(run func(code int)) *MockContext_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_Status_Call) Return() *MockContext_Status_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContext_Status_Call) RunAndReturn(run func(code int)) *MockContext_Status_Call {
	_c.Run(run)
	return _c
}

// String provides a mock function for the type MockContext
func (_mock *MockContext) String(code int, str string) error {
	ret := _mock.Called(code, str)

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = returnFunc(code, str)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContext_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockContext_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
//   - code int
//   - str string
func (_e *MockContext_Expecter) String(code interface{}, str interface{}) *MockContext_String_Call {
	return &MockContext_String_Call{Call: _e.mock.On("String", code, str)}
}

func (_c *MockContext_String_Call) Run(run func(code int, str string)) *MockContext_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContext_String_Call) Return(err error) *MockContext_String_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContext_String_Call) RunAndReturn(run func(code int, str string) error) *MockContext_String_Call {
	_c.Call.Return(run)
	return _c
}

// Value provides a mock function for the type MockContext
func (_mock *MockContext) Value(key any) any {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Value")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func(any) any); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockContext_Value_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Value'
type MockContext_Value_Call struct {
	*mock.Call
}

// Value is a helper method to define mock.On call
//   - key any
func (_e *MockContext_Expecter) Value(key interface{}) *MockContext_Value_Call {
	return &MockContext_Value_Call{Call: _e.mock.On("Value", key)}
}

func (_c *MockContext_Value_Call) Run(run func(key any)) *MockContext_Value_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContext_Value_Call) Return(v any) *MockContext_Value_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockContext_Value_Call) RunAndReturn(run func(key any) any) *MockContext_Value_Call {
	_c.Call.Return(run)
	return _c
}

// Writer provides a mock function for the type MockContext
func (_mock *MockContext) Writer() ResponseWriter {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Writer")
	}

	var r0 ResponseWriter
	if returnFunc, ok := ret.Get(0).(func() ResponseWriter); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ResponseWriter)
		}
	}
	return r0
}

// MockContext_Writer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Writer'
type MockContext_Writer_Call struct {
	*mock.Call
}

// Writer is a helper method to define mock.On call
func (_e *MockContext_Expecter) Writer() *MockContext_Writer_Call {
	return &MockContext_Writer_Call{Call: _e.mock.On("Writer")}
}

func (_c *MockContext_Writer_Call) Run(run func()) *MockContext_Writer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Writer_Call) Return(responseWriter ResponseWriter) *MockContext_Writer_Call {
	_c.Call.Return(responseWriter)
	return _c
}

func (_c *MockContext_Writer_Call) RunAndReturn(run func() ResponseWriter) *MockContext_Writer_Call {
	_c.Call.Return(run)
	return _c
}
