// Code generated by mockery v2.52.2. DO NOT EDIT.

package lit

import mock "github.com/stretchr/testify/mock"

// MockServerOption is an autogenerated mock type for the ServerOption type
type MockServerOption struct {
	mock.Mock
}

type MockServerOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerOption) EXPECT() *MockServerOption_Expecter {
	return &MockServerOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockServerOption) Execute(_a0 *Server) {
	_m.Called(_a0)
}

// MockServerOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockServerOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *Server
func (_e *MockServerOption_Expecter) Execute(_a0 interface{}) *MockServerOption_Execute_Call {
	return &MockServerOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockServerOption_Execute_Call) Run(run func(_a0 *Server)) *MockServerOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Server))
	})
	return _c
}

func (_c *MockServerOption_Execute_Call) Return() *MockServerOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerOption_Execute_Call) RunAndReturn(run func(*Server)) *MockServerOption_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockServerOption creates a new instance of MockServerOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerOption {
	mock := &MockServerOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
