// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package lit

import (
	"bufio"
	"net"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockResponseWriter creates a new instance of MockResponseWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResponseWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResponseWriter {
	mock := &MockResponseWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResponseWriter is an autogenerated mock type for the ResponseWriter type
type MockResponseWriter struct {
	mock.Mock
}

type MockResponseWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResponseWriter) EXPECT() *MockResponseWriter_Expecter {
	return &MockResponseWriter_Expecter{mock: &_m.Mock}
}

// CloseNotify provides a mock function for the type MockResponseWriter
func (_mock *MockResponseWriter) CloseNotify() <-chan bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseNotify")
	}

	var r0 <-chan bool
	if returnFunc, ok := ret.Get(0).(func() <-chan bool); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan bool)
		}
	}
	return r0
}

// MockResponseWriter_CloseNotify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseNotify'
type MockResponseWriter_CloseNotify_Call struct {
	*mock.Call
}

// CloseNotify is a helper method to define mock.On call
func (_e *MockResponseWriter_Expecter) CloseNotify() *MockResponseWriter_CloseNotify_Call {
	return &MockResponseWriter_CloseNotify_Call{Call: _e.mock.On("CloseNotify")}
}

func (_c *MockResponseWriter_CloseNotify_Call) Run(run func()) *MockResponseWriter_CloseNotify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResponseWriter_CloseNotify_Call) Return(boolCh <-chan bool) *MockResponseWriter_CloseNotify_Call {
	_c.Call.Return(boolCh)
	return _c
}

func (_c *MockResponseWriter_CloseNotify_Call) RunAndReturn(run func() <-chan bool) *MockResponseWriter_CloseNotify_Call {
	_c.Call.Return(run)
	return _c
}

// Flush provides a mock function for the type MockResponseWriter
func (_mock *MockResponseWriter) Flush() {
	_mock.Called()
	return
}

// MockResponseWriter_Flush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flush'
type MockResponseWriter_Flush_Call struct {
	*mock.Call
}

// Flush is a helper method to define mock.On call
func (_e *MockResponseWriter_Expecter) Flush() *MockResponseWriter_Flush_Call {
	return &MockResponseWriter_Flush_Call{Call: _e.mock.On("Flush")}
}

func (_c *MockResponseWriter_Flush_Call) Run(run func()) *MockResponseWriter_Flush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResponseWriter_Flush_Call) Return() *MockResponseWriter_Flush_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockResponseWriter_Flush_Call) RunAndReturn(run func()) *MockResponseWriter_Flush_Call {
	_c.Run(run)
	return _c
}

// Header provides a mock function for the type MockResponseWriter
func (_mock *MockResponseWriter) Header() http.Header {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 http.Header
	if returnFunc, ok := ret.Get(0).(func() http.Header); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}
	return r0
}

// MockResponseWriter_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type MockResponseWriter_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *MockResponseWriter_Expecter) Header() *MockResponseWriter_Header_Call {
	return &MockResponseWriter_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *MockResponseWriter_Header_Call) Run(run func()) *MockResponseWriter_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResponseWriter_Header_Call) Return(header http.Header) *MockResponseWriter_Header_Call {
	_c.Call.Return(header)
	return _c
}

func (_c *MockResponseWriter_Header_Call) RunAndReturn(run func() http.Header) *MockResponseWriter_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Hijack provides a mock function for the type MockResponseWriter
func (_mock *MockResponseWriter) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hijack")
	}

	var r0 net.Conn
	var r1 *bufio.ReadWriter
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (net.Conn, *bufio.ReadWriter, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() net.Conn); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() *bufio.ReadWriter); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bufio.ReadWriter)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockResponseWriter_Hijack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hijack'
type MockResponseWriter_Hijack_Call struct {
	*mock.Call
}

// Hijack is a helper method to define mock.On call
func (_e *MockResponseWriter_Expecter) Hijack() *MockResponseWriter_Hijack_Call {
	return &MockResponseWriter_Hijack_Call{Call: _e.mock.On("Hijack")}
}

func (_c *MockResponseWriter_Hijack_Call) Run(run func()) *MockResponseWriter_Hijack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResponseWriter_Hijack_Call) Return(conn net.Conn, readWriter *bufio.ReadWriter, err error) *MockResponseWriter_Hijack_Call {
	_c.Call.Return(conn, readWriter, err)
	return _c
}

func (_c *MockResponseWriter_Hijack_Call) RunAndReturn(run func() (net.Conn, *bufio.ReadWriter, error)) *MockResponseWriter_Hijack_Call {
	_c.Call.Return(run)
	return _c
}

// Pusher provides a mock function for the type MockResponseWriter
func (_mock *MockResponseWriter) Pusher() http.Pusher {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pusher")
	}

	var r0 http.Pusher
	if returnFunc, ok := ret.Get(0).(func() http.Pusher); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Pusher)
		}
	}
	return r0
}

// MockResponseWriter_Pusher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pusher'
type MockResponseWriter_Pusher_Call struct {
	*mock.Call
}

// Pusher is a helper method to define mock.On call
func (_e *MockResponseWriter_Expecter) Pusher() *MockResponseWriter_Pusher_Call {
	return &MockResponseWriter_Pusher_Call{Call: _e.mock.On("Pusher")}
}

func (_c *MockResponseWriter_Pusher_Call) Run(run func()) *MockResponseWriter_Pusher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResponseWriter_Pusher_Call) Return(pusher http.Pusher) *MockResponseWriter_Pusher_Call {
	_c.Call.Return(pusher)
	return _c
}

func (_c *MockResponseWriter_Pusher_Call) RunAndReturn(run func() http.Pusher) *MockResponseWriter_Pusher_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockResponseWriter
func (_mock *MockResponseWriter) Size() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockResponseWriter_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockResponseWriter_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockResponseWriter_Expecter) Size() *MockResponseWriter_Size_Call {
	return &MockResponseWriter_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockResponseWriter_Size_Call) Run(run func()) *MockResponseWriter_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResponseWriter_Size_Call) Return(n int) *MockResponseWriter_Size_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockResponseWriter_Size_Call) RunAndReturn(run func() int) *MockResponseWriter_Size_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockResponseWriter
func (_mock *MockResponseWriter) Status() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockResponseWriter_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockResponseWriter_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockResponseWriter_Expecter) Status() *MockResponseWriter_Status_Call {
	return &MockResponseWriter_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockResponseWriter_Status_Call) Run(run func()) *MockResponseWriter_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResponseWriter_Status_Call) Return(n int) *MockResponseWriter_Status_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockResponseWriter_Status_Call) RunAndReturn(run func() int) *MockResponseWriter_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type MockResponseWriter
func (_mock *MockResponseWriter) Write(bytes []byte) (int, error) {
	ret := _mock.Called(bytes)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(bytes)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(bytes)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResponseWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockResponseWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - bytes []byte
func (_e *MockResponseWriter_Expecter) Write(bytes interface{}) *MockResponseWriter_Write_Call {
	return &MockResponseWriter_Write_Call{Call: _e.mock.On("Write", bytes)}
}

func (_c *MockResponseWriter_Write_Call) Run(run func(bytes []byte)) *MockResponseWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResponseWriter_Write_Call) Return(n int, err error) *MockResponseWriter_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockResponseWriter_Write_Call) RunAndReturn(run func(bytes []byte) (int, error)) *MockResponseWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}

// WriteHeader provides a mock function for the type MockResponseWriter
func (_mock *MockResponseWriter) WriteHeader(statusCode int) {
	_mock.Called(statusCode)
	return
}

// MockResponseWriter_WriteHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteHeader'
type MockResponseWriter_WriteHeader_Call struct {
	*mock.Call
}

// WriteHeader is a helper method to define mock.On call
//   - statusCode int
func (_e *MockResponseWriter_Expecter) WriteHeader(statusCode interface{}) *MockResponseWriter_WriteHeader_Call {
	return &MockResponseWriter_WriteHeader_Call{Call: _e.mock.On("WriteHeader", statusCode)}
}

func (_c *MockResponseWriter_WriteHeader_Call) Run(run func(statusCode int)) *MockResponseWriter_WriteHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResponseWriter_WriteHeader_Call) Return() *MockResponseWriter_WriteHeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockResponseWriter_WriteHeader_Call) RunAndReturn(run func(statusCode int)) *MockResponseWriter_WriteHeader_Call {
	_c.Run(run)
	return _c
}

// WriteHeaderNow provides a mock function for the type MockResponseWriter
func (_mock *MockResponseWriter) WriteHeaderNow() {
	_mock.Called()
	return
}

// MockResponseWriter_WriteHeaderNow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteHeaderNow'
type MockResponseWriter_WriteHeaderNow_Call struct {
	*mock.Call
}

// WriteHeaderNow is a helper method to define mock.On call
func (_e *MockResponseWriter_Expecter) WriteHeaderNow() *MockResponseWriter_WriteHeaderNow_Call {
	return &MockResponseWriter_WriteHeaderNow_Call{Call: _e.mock.On("WriteHeaderNow")}
}

func (_c *MockResponseWriter_WriteHeaderNow_Call) Run(run func()) *MockResponseWriter_WriteHeaderNow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResponseWriter_WriteHeaderNow_Call) Return() *MockResponseWriter_WriteHeaderNow_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockResponseWriter_WriteHeaderNow_Call) RunAndReturn(run func()) *MockResponseWriter_WriteHeaderNow_Call {
	_c.Run(run)
	return _c
}

// WriteString provides a mock function for the type MockResponseWriter
func (_mock *MockResponseWriter) WriteString(s string) (int, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for WriteString")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResponseWriter_WriteString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteString'
type MockResponseWriter_WriteString_Call struct {
	*mock.Call
}

// WriteString is a helper method to define mock.On call
//   - s string
func (_e *MockResponseWriter_Expecter) WriteString(s interface{}) *MockResponseWriter_WriteString_Call {
	return &MockResponseWriter_WriteString_Call{Call: _e.mock.On("WriteString", s)}
}

func (_c *MockResponseWriter_WriteString_Call) Run(run func(s string)) *MockResponseWriter_WriteString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResponseWriter_WriteString_Call) Return(n int, err error) *MockResponseWriter_WriteString_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockResponseWriter_WriteString_Call) RunAndReturn(run func(s string) (int, error)) *MockResponseWriter_WriteString_Call {
	_c.Call.Return(run)
	return _c
}

// Written provides a mock function for the type MockResponseWriter
func (_mock *MockResponseWriter) Written() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Written")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockResponseWriter_Written_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Written'
type MockResponseWriter_Written_Call struct {
	*mock.Call
}

// Written is a helper method to define mock.On call
func (_e *MockResponseWriter_Expecter) Written() *MockResponseWriter_Written_Call {
	return &MockResponseWriter_Written_Call{Call: _e.mock.On("Written")}
}

func (_c *MockResponseWriter_Written_Call) Run(run func()) *MockResponseWriter_Written_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResponseWriter_Written_Call) Return(b bool) *MockResponseWriter_Written_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockResponseWriter_Written_Call) RunAndReturn(run func() bool) *MockResponseWriter_Written_Call {
	_c.Call.Return(run)
	return _c
}
