// Code generated by mockery v2.49.1. DO NOT EDIT.

package httpclient

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockPoolOption is an autogenerated mock type for the PoolOption type
type MockPoolOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockPoolOption) Execute(_a0 *http.Client) {
	_m.Called(_a0)
}

// NewMockPoolOption creates a new instance of MockPoolOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPoolOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPoolOption {
	mock := &MockPoolOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
