version: 2.1

executors:
  golang-executor:
    docker:
      - image: golang:1.23

jobs:
  # Dev Task
  dev-task:
    executor: golang-executor
    steps:
      - checkout
      - run:
          name: Run Go Tests
          command: go test -mod=vendor -coverprofile=coverage.out -failfast -timeout 5m ./...
      - persist_to_workspace:
          root: .
          paths:
            - coverage.out

  # Coverage
  coverage:
    executor: golang-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Setup Coveralls CLI
          command: GO111MODULE=on go install github.com/mattn/goveralls@latest
      - run:
          name: Save Coverage
          command: goveralls -coverprofile=coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
            

workflows:
  version: 2
  dev-workflow:
    jobs:
      - dev-task
      - coverage:
          requires:
            - dev-task
          filters:
            branches:
              only:
                - main