// Code generated by mockery v2.49.1. DO NOT EDIT.

package jwt

import mock "github.com/stretchr/testify/mock"

// MockClaims is an autogenerated mock type for the Claims type
type MockClaims struct {
	mock.Mock
}

// Valid provides a mock function with given fields:
func (_m *MockClaims) Valid() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Valid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockClaims creates a new instance of MockClaims. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClaims(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClaims {
	mock := &MockClaims{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
