// Code generated by mockery v2.49.1. DO NOT EDIT.

package jwt

import mock "github.com/stretchr/testify/mock"

// MockParserOptions is an autogenerated mock type for the ParserOptions type
type MockParserOptions struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockParserOptions) Execute(_a0 *Parser[Claims]) {
	_m.Called(_a0)
}

// NewMockParserOptions creates a new instance of MockParserOptions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParserOptions(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParserOptions {
	mock := &MockParserOptions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
