// Code generated by mockery v2.53.0. DO NOT EDIT.

package jwt

import mock "github.com/stretchr/testify/mock"

// MockParserOptions is an autogenerated mock type for the ParserOptions type
type MockParserOptions struct {
	mock.Mock
}

type MockParserOptions_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParserOptions) EXPECT() *MockParserOptions_Expecter {
	return &MockParserOptions_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockParserOptions) Execute(_a0 *Parser[Claims]) {
	_m.Called(_a0)
}

// MockParserOptions_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockParserOptions_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *Parser[Claims]
func (_e *MockParserOptions_Expecter) Execute(_a0 interface{}) *MockParserOptions_Execute_Call {
	return &MockParserOptions_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockParserOptions_Execute_Call) Run(run func(_a0 *Parser[Claims])) *MockParserOptions_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Parser[Claims]))
	})
	return _c
}

func (_c *MockParserOptions_Execute_Call) Return() *MockParserOptions_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockParserOptions_Execute_Call) RunAndReturn(run func(*Parser[Claims])) *MockParserOptions_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockParserOptions creates a new instance of MockParserOptions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParserOptions(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParserOptions {
	mock := &MockParserOptions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
