// Code generated by mockery v2.49.1. DO NOT EDIT.

package jwt

import mock "github.com/stretchr/testify/mock"

// MockVerifyKey is an autogenerated mock type for the VerifyKey type
type MockVerifyKey struct {
	mock.Mock
}

// NewMockVerifyKey creates a new instance of MockVerifyKey. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifyKey(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifyKey {
	mock := &MockVerifyKey{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
