// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jwt

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockClaims creates a new instance of MockClaims. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClaims(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClaims {
	mock := &MockClaims{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClaims is an autogenerated mock type for the Claims type
type MockClaims struct {
	mock.Mock
}

type MockClaims_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClaims) EXPECT() *MockClaims_Expecter {
	return &MockClaims_Expecter{mock: &_m.Mock}
}

// Valid provides a mock function for the type MockClaims
func (_mock *MockClaims) Valid() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Valid")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClaims_Valid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Valid'
type MockClaims_Valid_Call struct {
	*mock.Call
}

// Valid is a helper method to define mock.On call
func (_e *MockClaims_Expecter) Valid() *MockClaims_Valid_Call {
	return &MockClaims_Valid_Call{Call: _e.mock.On("Valid")}
}

func (_c *MockClaims_Valid_Call) Run(run func()) *MockClaims_Valid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_Valid_Call) Return(err error) *MockClaims_Valid_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClaims_Valid_Call) RunAndReturn(run func() error) *MockClaims_Valid_Call {
	_c.Call.Return(run)
	return _c
}
