// Code generated by mockery. DO NOT EDIT.

package redis

import mock "github.com/stretchr/testify/mock"

// MockType is an autogenerated mock type for the Type type
type MockType struct {
	mock.Mock
}

type MockType_Expecter struct {
	mock *mock.Mock
}

func (_m *MockType) EXPECT() *MockType_Expecter {
	return &MockType_Expecter{mock: &_m.Mock}
}

// NewMockType creates a new instance of MockType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockType(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockType {
	mock := &MockType{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
