// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package redis

import (
	"context"

	"github.com/redis/go-redis/v9"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRedisPubSub creates a new instance of MockRedisPubSub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedisPubSub(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedisPubSub {
	mock := &MockRedisPubSub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRedisPubSub is an autogenerated mock type for the RedisPubSub type
type MockRedisPubSub struct {
	mock.Mock
}

type MockRedisPubSub_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedisPubSub) EXPECT() *MockRedisPubSub_Expecter {
	return &MockRedisPubSub_Expecter{mock: &_m.Mock}
}

// Channel provides a mock function for the type MockRedisPubSub
func (_mock *MockRedisPubSub) Channel(opts ...redis.ChannelOption) <-chan *redis.Message {
	// redis.ChannelOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Channel")
	}

	var r0 <-chan *redis.Message
	if returnFunc, ok := ret.Get(0).(func(...redis.ChannelOption) <-chan *redis.Message); ok {
		r0 = returnFunc(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *redis.Message)
		}
	}
	return r0
}

// MockRedisPubSub_Channel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Channel'
type MockRedisPubSub_Channel_Call struct {
	*mock.Call
}

// Channel is a helper method to define mock.On call
//   - opts ...redis.ChannelOption
func (_e *MockRedisPubSub_Expecter) Channel(opts ...interface{}) *MockRedisPubSub_Channel_Call {
	return &MockRedisPubSub_Channel_Call{Call: _e.mock.On("Channel",
		append([]interface{}{}, opts...)...)}
}

func (_c *MockRedisPubSub_Channel_Call) Run(run func(opts ...redis.ChannelOption)) *MockRedisPubSub_Channel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []redis.ChannelOption
		variadicArgs := make([]redis.ChannelOption, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(redis.ChannelOption)
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockRedisPubSub_Channel_Call) Return(messageCh <-chan *redis.Message) *MockRedisPubSub_Channel_Call {
	_c.Call.Return(messageCh)
	return _c
}

func (_c *MockRedisPubSub_Channel_Call) RunAndReturn(run func(opts ...redis.ChannelOption) <-chan *redis.Message) *MockRedisPubSub_Channel_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockRedisPubSub
func (_mock *MockRedisPubSub) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedisPubSub_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockRedisPubSub_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockRedisPubSub_Expecter) Close() *MockRedisPubSub_Close_Call {
	return &MockRedisPubSub_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockRedisPubSub_Close_Call) Run(run func()) *MockRedisPubSub_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRedisPubSub_Close_Call) Return(err error) *MockRedisPubSub_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedisPubSub_Close_Call) RunAndReturn(run func() error) *MockRedisPubSub_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function for the type MockRedisPubSub
func (_mock *MockRedisPubSub) Receive(ctx context.Context) (interface{}, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (interface{}, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) interface{}); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRedisPubSub_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type MockRedisPubSub_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRedisPubSub_Expecter) Receive(ctx interface{}) *MockRedisPubSub_Receive_Call {
	return &MockRedisPubSub_Receive_Call{Call: _e.mock.On("Receive", ctx)}
}

func (_c *MockRedisPubSub_Receive_Call) Run(run func(ctx context.Context)) *MockRedisPubSub_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRedisPubSub_Receive_Call) Return(ifaceVal interface{}, err error) *MockRedisPubSub_Receive_Call {
	_c.Call.Return(ifaceVal, err)
	return _c
}

func (_c *MockRedisPubSub_Receive_Call) RunAndReturn(run func(ctx context.Context) (interface{}, error)) *MockRedisPubSub_Receive_Call {
	_c.Call.Return(run)
	return _c
}
