#stages:
#  - build
#  - push
#
#build_image:
#  stage: build
#  image: docker:latest
#  services:
#    - docker:dind
#  before_script:
#    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
#  script:
#    - if [ -n "$CI_COMMIT_TAG" ]; then export IMAGE_TAG=$CI_COMMIT_TAG; else echo "No tag found, skipping..."; exit 1; fi
#    - docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$IMAGE_TAG .
#  only:
#    - tags
#
#push_image:
#  stage: push
#  image: docker:latest
#  services:
#    - docker:dind
#  script:
#    - docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$IMAGE_TAG
#  only:
#    - tags
#  dependencies:
#    - build_image


#stages:
#  - build
#  - push
#
#build_image:
#  stage: build
#  image: docker:latest
#  services:
#    - docker:dind
#  before_script:
#    # Kiểm tra giá trị của biến
#    - echo "Docker username: $DOCKER_USERNAME"
#    - echo "Docker image name: $DOCKER_IMAGE_NAME"
#    # Đăng nhập vào Docker Hub
#    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#  script:
#    - if [ -n "$CI_COMMIT_TAG" ]; then IMAGE_TAG=$CI_COMMIT_TAG; echo "Building image with tag: $IMAGE_TAG"; else echo "No tag found, skipping..."; exit 1; fi
#    - docker build -t "$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$IMAGE_TAG" .
#  rules:
#    - if: '$CI_COMMIT_TAG =~ /^Release v\d+\.\d+\.\d+$/'
#
#push_image:
#  stage: push
#  image: docker:latest
#  services:
#    - docker:dind
#  script:
#    - echo "Pushing image $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$IMAGE_TAG"
#    - docker push "$DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$IMAGE_TAG"
#  rules:
#    - if: '$CI_COMMIT_TAG =~ /^Release v\d+\.\d+\.\d+$/'
#  dependencies:
#    - build_image
