// Code generated by mockery v2.49.1. DO NOT EDIT.

package testdata

import mock "github.com/stretchr/testify/mock"

// MockUnsafeWeatherServiceServer is an autogenerated mock type for the UnsafeWeatherServiceServer type
type MockUnsafeWeatherServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedWeatherServiceServer provides a mock function with given fields:
func (_m *MockUnsafeWeatherServiceServer) mustEmbedUnimplementedWeatherServiceServer() {
	_m.Called()
}

// NewMockUnsafeWeatherServiceServer creates a new instance of MockUnsafeWeatherServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeWeatherServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeWeatherServiceServer {
	mock := &MockUnsafeWeatherServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
