// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package i18n

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockLocalizable creates a new instance of MockLocalizable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocalizable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocalizable {
	mock := &MockLocalizable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLocalizable is an autogenerated mock type for the Localizable type
type MockLocalizable struct {
	mock.Mock
}

type MockLocalizable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocalizable) EXPECT() *MockLocalizable_Expecter {
	return &MockLocalizable_Expecter{mock: &_m.Mock}
}

// Localize provides a mock function for the type MockLocalizable
func (_mock *MockLocalizable) Localize(messageID string, params map[string]interface{}) string {
	ret := _mock.Called(messageID, params)

	if len(ret) == 0 {
		panic("no return value specified for Localize")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, map[string]interface{}) string); ok {
		r0 = returnFunc(messageID, params)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockLocalizable_Localize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Localize'
type MockLocalizable_Localize_Call struct {
	*mock.Call
}

// Localize is a helper method to define mock.On call
//   - messageID string
//   - params map[string]interface{}
func (_e *MockLocalizable_Expecter) Localize(messageID interface{}, params interface{}) *MockLocalizable_Localize_Call {
	return &MockLocalizable_Localize_Call{Call: _e.mock.On("Localize", messageID, params)}
}

func (_c *MockLocalizable_Localize_Call) Run(run func(messageID string, params map[string]interface{})) *MockLocalizable_Localize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLocalizable_Localize_Call) Return(s string) *MockLocalizable_Localize_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockLocalizable_Localize_Call) RunAndReturn(run func(messageID string, params map[string]interface{}) string) *MockLocalizable_Localize_Call {
	_c.Call.Return(run)
	return _c
}

// TryLocalize provides a mock function for the type MockLocalizable
func (_mock *MockLocalizable) TryLocalize(messageID string, params map[string]interface{}) (string, error) {
	ret := _mock.Called(messageID, params)

	if len(ret) == 0 {
		panic("no return value specified for TryLocalize")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, map[string]interface{}) (string, error)); ok {
		return returnFunc(messageID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(string, map[string]interface{}) string); ok {
		r0 = returnFunc(messageID, params)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, map[string]interface{}) error); ok {
		r1 = returnFunc(messageID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLocalizable_TryLocalize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryLocalize'
type MockLocalizable_TryLocalize_Call struct {
	*mock.Call
}

// TryLocalize is a helper method to define mock.On call
//   - messageID string
//   - params map[string]interface{}
func (_e *MockLocalizable_Expecter) TryLocalize(messageID interface{}, params interface{}) *MockLocalizable_TryLocalize_Call {
	return &MockLocalizable_TryLocalize_Call{Call: _e.mock.On("TryLocalize", messageID, params)}
}

func (_c *MockLocalizable_TryLocalize_Call) Run(run func(messageID string, params map[string]interface{})) *MockLocalizable_TryLocalize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLocalizable_TryLocalize_Call) Return(s string, err error) *MockLocalizable_TryLocalize_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLocalizable_TryLocalize_Call) RunAndReturn(run func(messageID string, params map[string]interface{}) (string, error)) *MockLocalizable_TryLocalize_Call {
	_c.Call.Return(run)
	return _c
}
