// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package instrumentkafka

import (
	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/trace"
)

// NewMockPublishSegment creates a new instance of MockPublishSegment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublishSegment(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublishSegment {
	mock := &MockPublishSegment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPublishSegment is an autogenerated mock type for the PublishSegment type
type MockPublishSegment struct {
	mock.Mock
}

type MockPublishSegment_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublishSegment) EXPECT() *MockPublishSegment_Expecter {
	return &MockPublishSegment_Expecter{mock: &_m.Mock}
}

// End provides a mock function for the type MockPublishSegment
func (_mock *MockPublishSegment) End(partition int32, offset int64, sendErr error) {
	_mock.Called(partition, offset, sendErr)
	return
}

// MockPublishSegment_End_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'End'
type MockPublishSegment_End_Call struct {
	*mock.Call
}

// End is a helper method to define mock.On call
//   - partition int32
//   - offset int64
//   - sendErr error
func (_e *MockPublishSegment_Expecter) End(partition interface{}, offset interface{}, sendErr interface{}) *MockPublishSegment_End_Call {
	return &MockPublishSegment_End_Call{Call: _e.mock.On("End", partition, offset, sendErr)}
}

func (_c *MockPublishSegment_End_Call) Run(run func(partition int32, offset int64, sendErr error)) *MockPublishSegment_End_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPublishSegment_End_Call) Return() *MockPublishSegment_End_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPublishSegment_End_Call) RunAndReturn(run func(partition int32, offset int64, sendErr error)) *MockPublishSegment_End_Call {
	_c.Run(run)
	return _c
}

// SpanContext provides a mock function for the type MockPublishSegment
func (_mock *MockPublishSegment) SpanContext() trace.SpanContext {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SpanContext")
	}

	var r0 trace.SpanContext
	if returnFunc, ok := ret.Get(0).(func() trace.SpanContext); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(trace.SpanContext)
	}
	return r0
}

// MockPublishSegment_SpanContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SpanContext'
type MockPublishSegment_SpanContext_Call struct {
	*mock.Call
}

// SpanContext is a helper method to define mock.On call
func (_e *MockPublishSegment_Expecter) SpanContext() *MockPublishSegment_SpanContext_Call {
	return &MockPublishSegment_SpanContext_Call{Call: _e.mock.On("SpanContext")}
}

func (_c *MockPublishSegment_SpanContext_Call) Run(run func()) *MockPublishSegment_SpanContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPublishSegment_SpanContext_Call) Return(spanContext trace.SpanContext) *MockPublishSegment_SpanContext_Call {
	_c.Call.Return(spanContext)
	return _c
}

func (_c *MockPublishSegment_SpanContext_Call) RunAndReturn(run func() trace.SpanContext) *MockPublishSegment_SpanContext_Call {
	_c.Call.Return(run)
	return _c
}

// SpanID provides a mock function for the type MockPublishSegment
func (_mock *MockPublishSegment) SpanID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SpanID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPublishSegment_SpanID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SpanID'
type MockPublishSegment_SpanID_Call struct {
	*mock.Call
}

// SpanID is a helper method to define mock.On call
func (_e *MockPublishSegment_Expecter) SpanID() *MockPublishSegment_SpanID_Call {
	return &MockPublishSegment_SpanID_Call{Call: _e.mock.On("SpanID")}
}

func (_c *MockPublishSegment_SpanID_Call) Run(run func()) *MockPublishSegment_SpanID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPublishSegment_SpanID_Call) Return(s string) *MockPublishSegment_SpanID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPublishSegment_SpanID_Call) RunAndReturn(run func() string) *MockPublishSegment_SpanID_Call {
	_c.Call.Return(run)
	return _c
}
