// Code generated by mockery v2.49.1. DO NOT EDIT.

package iam

import mock "github.com/stretchr/testify/mock"

// MockEnforcer is an autogenerated mock type for the Enforcer type
type MockEnforcer struct {
	mock.Mock
}

// Enforce provides a mock function with given fields: sub, obj, act
func (_m *MockEnforcer) Enforce(sub string, obj string, act string) error {
	ret := _m.Called(sub, obj, act)

	if len(ret) == 0 {
		panic("no return value specified for Enforce")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(sub, obj, act)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockEnforcer creates a new instance of MockEnforcer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnforcer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnforcer {
	mock := &MockEnforcer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
