// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package iam

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/viebiz/lit/jwt"
)

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockValidator
func (_mock *MockValidator) Validate(tokenString string) (jwt.Token[Claims], error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 jwt.Token[Claims]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (jwt.Token[Claims], error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) jwt.Token[Claims]); ok {
		r0 = returnFunc(tokenString)
	} else {
		r0 = ret.Get(0).(jwt.Token[Claims])
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - tokenString string
func (_e *MockValidator_Expecter) Validate(tokenString interface{}) *MockValidator_Validate_Call {
	return &MockValidator_Validate_Call{Call: _e.mock.On("Validate", tokenString)}
}

func (_c *MockValidator_Validate_Call) Run(run func(tokenString string)) *MockValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockValidator_Validate_Call) Return(token jwt.Token[Claims], err error) *MockValidator_Validate_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockValidator_Validate_Call) RunAndReturn(run func(tokenString string) (jwt.Token[Claims], error)) *MockValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
