// Code generated by mockery. DO NOT EDIT.

package iam

import (
	mock "github.com/stretchr/testify/mock"
	jwt "github.com/viebiz/lit/jwt"
)

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with given fields: tokenString
func (_m *MockValidator) Validate(tokenString string) (jwt.Token[Claims], error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 jwt.Token[Claims]
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (jwt.Token[Claims], error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) jwt.Token[Claims]); ok {
		r0 = rf(tokenString)
	} else {
		r0 = ret.Get(0).(jwt.Token[Claims])
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - tokenString string
func (_e *MockValidator_Expecter) Validate(tokenString interface{}) *MockValidator_Validate_Call {
	return &MockValidator_Validate_Call{Call: _e.mock.On("Validate", tokenString)}
}

func (_c *MockValidator_Validate_Call) Run(run func(tokenString string)) *MockValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockValidator_Validate_Call) Return(_a0 jwt.Token[Claims], _a1 error) *MockValidator_Validate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockValidator_Validate_Call) RunAndReturn(run func(string) (jwt.Token[Claims], error)) *MockValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
