// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package postgres

import (
	"database/sql"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactor creates a new instance of MockTransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactor {
	mock := &MockTransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactor is an autogenerated mock type for the Transactor type
type MockTransactor struct {
	mock.Mock
}

type MockTransactor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactor) EXPECT() *MockTransactor_Expecter {
	return &MockTransactor_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type MockTransactor
func (_mock *MockTransactor) Commit() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactor_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockTransactor_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *MockTransactor_Expecter) Commit() *MockTransactor_Commit_Call {
	return &MockTransactor_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *MockTransactor_Commit_Call) Run(run func()) *MockTransactor_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactor_Commit_Call) Return(err error) *MockTransactor_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactor_Commit_Call) RunAndReturn(run func() error) *MockTransactor_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type MockTransactor
func (_mock *MockTransactor) Exec(query string, args ...interface{}) (sql.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 sql.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) (sql.Result, error)); ok {
		return returnFunc(query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) sql.Result); ok {
		r0 = returnFunc(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = returnFunc(query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactor_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockTransactor_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - query string
//   - args ...interface{}
func (_e *MockTransactor_Expecter) Exec(query interface{}, args ...interface{}) *MockTransactor_Exec_Call {
	return &MockTransactor_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{query}, args...)...)}
}

func (_c *MockTransactor_Exec_Call) Run(run func(query string, args ...interface{})) *MockTransactor_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTransactor_Exec_Call) Return(result sql.Result, err error) *MockTransactor_Exec_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockTransactor_Exec_Call) RunAndReturn(run func(query string, args ...interface{}) (sql.Result, error)) *MockTransactor_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Prepare provides a mock function for the type MockTransactor
func (_mock *MockTransactor) Prepare(query string) (*sql.Stmt, error) {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 *sql.Stmt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*sql.Stmt, error)); ok {
		return returnFunc(query)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *sql.Stmt); ok {
		r0 = returnFunc(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactor_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type MockTransactor_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - query string
func (_e *MockTransactor_Expecter) Prepare(query interface{}) *MockTransactor_Prepare_Call {
	return &MockTransactor_Prepare_Call{Call: _e.mock.On("Prepare", query)}
}

func (_c *MockTransactor_Prepare_Call) Run(run func(query string)) *MockTransactor_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactor_Prepare_Call) Return(stmt *sql.Stmt, err error) *MockTransactor_Prepare_Call {
	_c.Call.Return(stmt, err)
	return _c
}

func (_c *MockTransactor_Prepare_Call) RunAndReturn(run func(query string) (*sql.Stmt, error)) *MockTransactor_Prepare_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockTransactor
func (_mock *MockTransactor) Query(query string, args ...interface{}) (*sql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *sql.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) (*sql.Rows, error)); ok {
		return returnFunc(query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) *sql.Rows); ok {
		r0 = returnFunc(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = returnFunc(query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactor_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockTransactor_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - query string
//   - args ...interface{}
func (_e *MockTransactor_Expecter) Query(query interface{}, args ...interface{}) *MockTransactor_Query_Call {
	return &MockTransactor_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{query}, args...)...)}
}

func (_c *MockTransactor_Query_Call) Run(run func(query string, args ...interface{})) *MockTransactor_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTransactor_Query_Call) Return(rows *sql.Rows, err error) *MockTransactor_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockTransactor_Query_Call) RunAndReturn(run func(query string, args ...interface{}) (*sql.Rows, error)) *MockTransactor_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type MockTransactor
func (_mock *MockTransactor) QueryRow(query string, args ...interface{}) *sql.Row {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 *sql.Row
	if returnFunc, ok := ret.Get(0).(func(string, ...interface{}) *sql.Row); ok {
		r0 = returnFunc(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}
	return r0
}

// MockTransactor_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockTransactor_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - query string
//   - args ...interface{}
func (_e *MockTransactor_Expecter) QueryRow(query interface{}, args ...interface{}) *MockTransactor_QueryRow_Call {
	return &MockTransactor_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{query}, args...)...)}
}

func (_c *MockTransactor_QueryRow_Call) Run(run func(query string, args ...interface{})) *MockTransactor_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTransactor_QueryRow_Call) Return(row *sql.Row) *MockTransactor_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *MockTransactor_QueryRow_Call) RunAndReturn(run func(query string, args ...interface{}) *sql.Row) *MockTransactor_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockTransactor
func (_mock *MockTransactor) Rollback() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactor_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockTransactor_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
func (_e *MockTransactor_Expecter) Rollback() *MockTransactor_Rollback_Call {
	return &MockTransactor_Rollback_Call{Call: _e.mock.On("Rollback")}
}

func (_c *MockTransactor_Rollback_Call) Run(run func()) *MockTransactor_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactor_Rollback_Call) Return(err error) *MockTransactor_Rollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactor_Rollback_Call) RunAndReturn(run func() error) *MockTransactor_Rollback_Call {
	_c.Call.Return(run)
	return _c
}
