// Code generated by mockery. DO NOT EDIT.

package postgres

import (
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"
)

// MockBeginner is an autogenerated mock type for the Beginner type
type MockBeginner struct {
	mock.Mock
}

type MockBeginner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBeginner) EXPECT() *MockBeginner_Expecter {
	return &MockBeginner_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with no fields
func (_m *MockBeginner) Begin() (*sql.Tx, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 *sql.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func() (*sql.Tx, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *sql.Tx); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBeginner_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockBeginner_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
func (_e *MockBeginner_Expecter) Begin() *MockBeginner_Begin_Call {
	return &MockBeginner_Begin_Call{Call: _e.mock.On("Begin")}
}

func (_c *MockBeginner_Begin_Call) Run(run func()) *MockBeginner_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBeginner_Begin_Call) Return(_a0 *sql.Tx, _a1 error) *MockBeginner_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBeginner_Begin_Call) RunAndReturn(run func() (*sql.Tx, error)) *MockBeginner_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBeginner creates a new instance of MockBeginner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBeginner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBeginner {
	mock := &MockBeginner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
