// Code generated by mockery v2.52.2. DO NOT EDIT.

package env

import mock "github.com/stretchr/testify/mock"

// MockAppConfig is an autogenerated mock type for the AppConfig type
type MockAppConfig struct {
	mock.Mock
}

type MockAppConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppConfig) EXPECT() *MockAppConfig_Expecter {
	return &MockAppConfig_Expecter{mock: &_m.Mock}
}

// NewMockAppConfig creates a new instance of MockAppConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppConfig {
	mock := &MockAppConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
