name: Lightning CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    environment: ${{ github.ref == 'refs/heads/main' && 'PROD' || 'DEV' }}
    permissions:
      contents: write
      actions: write
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run Unit Tests
        env:
          DATABASE_URL: ${{ secrets.PG_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: make test
